### ISSUE TITLE
ngx_pagespeed 1.10.33.5 dynamic module compile failed

### ISSUE THREAD

**Issue by centminmod** [pagespeed/ngx_pagespeed#1121]
* With CentOS 6.7 + ngx_pagespeed 1.10.33.5 + devtoolset-3 GCC 4.9.1, dynamic module compilation against Nginx 1.9.11 fails https://community.centminmod.com/posts/26773/. Gist of the failed compile's configure output https://gist.github.com/centminmod/d49f96d64d03ac2240ab with missing ngx_pagespeed.so
```
configuring additional dynamic modules
adding module in ../ngx_pagespeed-release-1.10.33.5-beta
dirname: extra operand `/opt/rh/devtoolset-3/root/usr/bin/gcc'
Try `dirname --help' for more information.
mod_pagespeed_dir=../ngx_pagespeed-release-1.10.33.5-beta/psol/include
build_from_source=false
checking for psol ... found
List of modules (in reverse order of applicability): ngx_http_write_filter_module ngx_http_header_filter_module ngx_http_chunked_filter_module ngx_http_v2_filter_module ngx_http_range_header_filter_module ngx_pagespeed_etag_filter ngx_http_gzip_filter_module ngx_pagespeed ngx_http_postpone_filter_module ngx_http_ssi_filter_module ngx_http_charset_filter_module ngx_http_sub_filter_module ngx_http_addition_filter_module ngx_http_userid_filter_module ngx_http_headers_filter_module
checking for psol-compiler-compat ... found
 + ngx_pagespeed was configured
```
* However, static ngx_pagespeed 1.10.33.5 + devtoolset-3 GCC 4.9.1 on Nginx 1.9.11 + CentOS 6.7 (same server) compiles successfully (haven't tested if ngx_pagespeed works just compile works) https://community.centminmod.com/posts/26773/

### working static ngx_pagespeed 1.10.33.5 config flags

> nginx -V
> nginx version: nginx/1.9.11
> built by gcc 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC)
> built with LibreSSL 2.2.6
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module **--add-module=../ngx_pagespeed-release-1.10.33.5-beta** --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-0.3.6 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.29 --with-pcre=../pcre-8.38 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.2.6

### failed dynamic module ngx_pagespeed 1.10.33.5 config flags with missing ngx_pagespeed.so

> nginx -V
> nginx version: nginx/1.9.11
> built by gcc 4.9.1 20140922 (Red Hat 4.9.1-10) (GCC)
> built with LibreSSL 2.2.6
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-lrt -ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -mtune=native -mfpmath=sse -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --with-openssl-opt=enable-tlsext --add-module=../nginx-module-vts --with-libatomic --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_gzip_static_module **--add-dynamic-module=../ngx_pagespeed-release-1.10.33.5-beta** --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_realip_module --add-module=../nginx-accesskey-2.0.3 --add-module=../nginx-http-concat-master --add-module=../ngx-fancyindex-0.3.6 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.2.19 --add-module=../set-misc-nginx-module-0.29 --add-module=../echo-nginx-module-0.58 --add-module=../redis2-nginx-module-0.12 --add-module=../ngx_http_redis-0.3.7 --add-module=../nginx_upstream_check_module-0.3.0 --add-module=../openresty-memc-nginx-module-4f6f78f --add-module=../openresty-srcache-nginx-module-ffa9ab7 --add-module=../headers-more-nginx-module-0.29 --with-pcre=../pcre-8.38 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../libressl-2.2.6

**Comment by centminmod** [comment]
could it be related to me using ccache compiler caching ?
```
export CC="ccache /opt/rh/devtoolset-3/root/usr/bin/gcc"
export CXX="ccache /opt/rh/devtoolset-3/root/usr/bin/g++"
```

**Comment by oschaaf** [comment]
@centminmod I'm building a centos VM too see if I can reproduce

**Comment by centminmod** [comment]
@oschaaf yeah CentOS 6.7 with devtoolset-3 + ccache compiler seems to be what is causing problem - updated some tests in above post HTH :)

**Comment by centminmod** [comment]
maybe instead of

```
export CC="ccache /opt/rh/devtoolset-3/root/usr/bin/gcc"
basename $CC| sed s/gcc/g++/
ccache
```

use

```
export CC="ccache /opt/rh/devtoolset-3/root/usr/bin/gcc"
echo $CC | sed s/gcc/g++/
ccache /opt/rh/devtoolset-3/root/usr/bin/g++

```

**Comment by centminmod** [comment]
looks like even if remove ccache still problematic
`export CC="/opt/rh/devtoolset-3/root/usr/bin/gcc"`
```
configuring additional dynamic modules
adding module in ../ngx_pagespeed-release-1.10.33.5-beta
dirname: extra operand `/opt/rh/devtoolset-3/root/usr/bin/gcc'
Try `dirname --help' for more information.
mod_pagespeed_dir=../ngx_pagespeed-release-1.10.33.5-beta/psol/include
build_from_source=false
checking for psol ... found
```

**Comment by xseven007** [comment]
I was configured it with 
./configure --with-cc-opt='-g -O3 -pipe -march=native -msse4.2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' --with-ld-opt='-Wl,-Bsymbolic-functions -fPIE -pie -Wl,-z,relro -Wl,-z,now' --prefix=/website/opt --modules-path=/website/opt/lib/nginx/modules --conf-path=/website/opt/etc/nginx/nginx.conf --http-log-path=/website/var/log/nginx/access.log --error-log-path=/website/var/log/nginx/error.log --lock-path=/website/var/run/nginx.lock --pid-path=/website/var/run/nginx.pid --http-client-body-temp-path=/website/cache/nginx/body --http-fastcgi-temp-path=/website/cache/nginx/fastcgi --http-proxy-temp-path=/website/cache/nginx/proxy --http-scgi-temp-path=/website/cache/nginx/scgi --http-uwsgi-temp-path=/website/cache/nginx/uwsgi --with-threads --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module --with-http_image_filter_module --with-http_geoip_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_stub_status_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-google_perftools_module --with-pcre --with-pcre-jit --with-debug --with-openssl=/root/src/openssl-1.0.2 --with-openssl-opt=-fPIC --add-dynamic-module=ngx_pagespeed-release-${NPS_VERSION}-beta

And I can not found any .so file in nginx-1.9.11/objs/addon/src, but there are many .o files

**Comment by oschaaf** [comment]
@xseven007  I think `ngx_pagespeed.so` files ends up in `modules/` directory in parallel to where you install `sbin/nginx`. So I do not expect it to be in `objs/`.

**Comment by oschaaf** [comment]
@centminmod 

Please note that `1.10.33.5` has not been announced yet, and that the release branch for the that version does not seem to have a the correct patches for supporting dynamic modules.

Releases are announced here: https://groups.google.com/forum/#!forum/ngx-pagespeed-announce

**Comment by xseven007** [comment]
@oschaaf I have found that there is not a ngx_pagespeed.so in any directory in the nginx's src directory or the sbin/nginx where I installed

**Comment by oschaaf** [comment]
@xseven007 No, I debugged a little but and understand why that is, see above, https://github.com/pagespeed/ngx_pagespeed/issues/1121#issuecomment-185151361

**Comment by centminmod** [comment]
@oschaaf ah i thought it was officially released as it's published at https://developers.google.com/speed/pagespeed/module/release_notes#release_1.10.33.5-beta

**Comment by crowell** [comment]
The release is just about done, the packages and code are all available,
except the git tag hasn't been made yet, I'm working to get that out soon
(today)

**Comment by centminmod** [comment]
see 1.10.33.5 was announced, so this time tried on CentOS 7.2 and similar problem as above with ngx_pagespeed having difficulties with manipulating the $CC variable derived basename and dirname due to unexpected $CC values

```
configuring additional dynamic modules
adding module in ../ngx_pagespeed-release-1.10.33.5-beta
basename: extra operand '-ferror-limit=0'
Try 'basename --help' for more information.
dirname: invalid option -- 'f'
Try 'dirname --help' for more information.
mod_pagespeed_dir=../ngx_pagespeed-release-1.10.33.5-beta/psol/include
build_from_source=false
checking for psol ... found
List of modules (in reverse order of applicability): ngx_http_write_filter_module ngx_http_header_filter_module ngx_http_chunked_filter_module ngx_http_v2_filter_module ngx_http_range_header_filter_module ngx_pagespeed_etag_filter ngx_http_gzip_filter_module ngx_pagespeed ngx_http_postpone_filter_module ngx_http_ssi_filter_module ngx_http_charset_filter_module ngx_http_sub_filter_module ngx_http_addition_filter_module ngx_http_userid_filter_module ngx_http_headers_filter_module
checking for psol-compiler-compat ... found
 + ngx_pagespeed was configured
```

**Comment by oschaaf** [comment]
@centminmod  /cc @crowell One thing I noticed is that the `config` file offered in https://github.com/pagespeed/ngx_pagespeed/archive/release-1.10.33.5-beta.zip differs from the tagged version (https://github.com/pagespeed/ngx_pagespeed/blob/4ec7afe5a8621a111b05ab2b42179cb623f19369/config) 

With the version offered in the zip, I'm not able to build `ngx_pagespeed.so`, but when I pull in the tagged version I am able to build ngx_pagespeed.so on a freshly built CentOS 6.7 OS VM.

@centminmod Could you try what happens with the tagged version of `config` that I linked? I that still does not work, we need to look into this more

**Comment by centminmod** [comment]
bit confused the tagged version is https://github.com/pagespeed/ngx_pagespeed/archive/release-1.10.33.5-beta.zip though ?

this is the download I am using
```
NGXPGSPEED_VER='1.10.33.5-beta'
NGX_PAGESPEEDLINKFILE="release-${NGXPGSPEED_VER}.tar.gz"
NGX_PAGESPEEDLINK="https://github.com/pagespeed/ngx_pagespeed/archive/${NGX_PAGESPEEDLINKFILE}"
```

**Comment by crowell** [comment]
The release zip should be generated from the tag, I'm a bit confused as to
how this could be happening

**Comment by centminmod** [comment]
strange indeed here's a rev diff of the different config files https://gist.github.com/centminmod/15bdaf8a5d8441377c34/revisions

**Comment by crowell** [comment]
@centminmod should be fixed, please try again!

**Comment by centminmod** [comment]
@crowell @oschaaf sweet goodness it works !

confirmed on CentOS 7.2 with Centmin Mod LEMP stack https://community.centminmod.com/posts/26842/ :+1:

**Comment by oschaaf** [comment]
@centminmod good to hear that it is working!

**Comment by centminmod** [comment]
@oschaaf yup confirmed works on CentOS 6.7 too https://community.centminmod.com/posts/26858/ :)

**Comment by centminmod** [comment]
seems updated to 1.9.12 and still get minor problem with dirname determination due to ccache set in $CC variable
```
configuring additional dynamic modules
adding module in ../ngx_pagespeed-release-1.10.33.5-beta
dirname: extra operand `gcc'
Try `dirname --help' for more information.
mod_pagespeed_dir=../ngx_pagespeed-release-1.10.33.5-beta/psol/include
build_from_source=false
checking for psol ... found
List of modules (in reverse order of applicability): ngx_http_write_filter_module ngx_http_header_filter_module ngx_http_chunked_filter_module ngx_http_v2_filter_module ngx_http_range_header_filter_module ngx_http_gzip_filter_module ngx_http_brotli_filter_module ngx_http_postpone_filter_module ngx_http_ssi_filter_module ngx_http_charset_filter_module ngx_http_sub_filter_module ngx_http_addition_filter_module ngx_http_userid_filter_module ngx_http_headers_filter_module
checking for psol-compiler-compat ... found
 + ngx_pagespeed was configured
```

**Comment by oschaaf** [comment]
@centminmod 
Is `export CC="ccache /path/to/gcc"` all that is needed for reproducing the `dirname: extra operand` message?
Do you, by chance, have a fix you can propose?

**Comment by centminmod** [comment]
well yes the problem with dirname seems to specifically related to ccache in front and centos 6.x and centos 7.x

```
source scl_source enable devtoolset-3
CC="ccache gcc"
ps_maybe_gpp="`dirname $CC`/$ps_maybe_gpp_base"
dirname: extra operand `gcc'
Try `dirname --help' for more information.
```
```
dirname $CC
dirname: extra operand `gcc'
Try `dirname --help' for more information.
```
```
ps_maybe_gpp_base=`basename $CC| sed s/gcc/g++/`
ps_maybe_gpp="`dirname $CC`/$ps_maybe_gpp_base"
echo $ps_maybe_gpp_base
echo $ps_maybe_gpp
```
on CentOS 6.7 results in
```
echo $ps_maybe_gpp_base
ccache
echo $ps_maybe_gpp
/ccache
```
on CentOS 7.2 results in
```
echo $ps_maybe_gpp_base
ccache
echo $ps_maybe_gpp
. ./ccache
```

maybe hacky approach would be to check if ccache is installed or in use and strip it from $CC first ?
```
if [[ "$(echo $CC | grep ccache >/dev/null 2>&1; echo $?)" -eq '0' ]]; then
  CC=$(echo $CC | sed -e 's|ccache ||')
fi
```

**Comment by centminmod** [comment]
Also why not just grab the environment `g++` and use that instead of using basename and dirname ?

On CentOS 6.7 without devtoolset-3 GCC 4.9.1 and with
```
which g++
/usr/bin/g++
```
```
source scl_source enable devtoolset-3
which g++
/opt/rh/devtoolset-3/root/usr/bin/g++
```
or just sed replace gcc with g++ in CC variable without using dirname and basename ?
```
echo $CC
ccache gcc
```
```
echo $CC | sed s/gcc/g++/
ccache g++
```

**Comment by oschaaf** [comment]
@morlovich See above, the way we use `dirname` seems to break when `ccache` is involved. Do you have any thoughts on the suggestions @centminmod made?

**Comment by morlovich** [comment]
Thanks for pinging me. Should probably just be dirname "$CC", and likewise for basename?

The reason we don't grab g++ is that we would like clang to work, though that seems to have other troubles.

**Comment by oschaaf** [comment]
@morlovich what about this suggestion from @centminmod:

```
CC_VAR=$(echo $CC | sed -e 's|ccache ||')
ps_maybe_gpp_base=`basename $CC_VAR| sed s/gcc/g++/`
ps_maybe_gpp="`dirname $CC_VAR`/$ps_maybe_gpp_base"
```

Just stripping `ccache` from `$CC` would fix the problem he's seeing, but I'm not sure if people stuff any other things in $CC that would break our usage of `dirname` (which is getting more arguments then it is expecting when `ccache` is involved).

**Comment by jeffkaufman** [comment]
What if we raised an error if we found spaces in `$CC`, and asked people to run us with `CC=gcc`?
