### ISSUE TITLE
Brotli gzip issue

### ISSUE THREAD

**Issue by Lofesa** [pagespeed/ngx_pagespeed#1345]
Background of this issue can be viewed [here](https://groups.google.com/forum/#!topic/ngx-pagespeed-discuss/g4iaCRRIl9M)

In a site with both brotli and gzip compression enabled, optimized resources are served with gzip and unoptimized resources with brotli. If "pagespeed HttpCacheCompressionLevel" is set to 0, both optimized and unoptimized resources are served with br but header Vary: Accept-Encoding is lost.
This behavior is new in 1.12.33.1, with version 1.11.33.4 both resources are served with br.

**Comment by jmarantz** [comment]
I think the 1.12 behavior is correct and expected.

If you enable PageSpeed's compressed cache, PageSpeed will serve its
optimized resources directly out of its cache, pre-compressed, with
Vary:Accept-Encoding. The Brotli module will probably not inflate and then
recompress the asset.

If you disable PageSpeed's compressed cache, then PageSpeed will not add
the Vary:Accept-Encoding header, because it's not necessary.  Any
downstream on-the-fly compression module (gzip or brotli) would then be
responsible for adding Vary:Accept-Encoding for assets they compress.

-Josh

**Comment by Lofesa** [comment]
Hi @jmarantz 
Server has an "add_header Vary Accept-encoding;" directive that NPS supresses in resources that it optimizes, I think that the module must leave this header, in fact resources that are not allowed to NPS has it.

**Comment by jmarantz** [comment]
OK I have to admit I'm not an nginx expert.  But IMO Vary:Accept-Encoding
should not be added by a configuration directive.  It should be added by
the module that caused the encoding to vary on the Accept-Encoding request
header.

In this case, NPS has inflated any upstream gzipped content so it can parse
and optimize it. When it did that, it removed the Vary:Accept-Encoding
header because the content no longer varies as far as NPS is concerned.
And NPS (because you turned cache-compression off) has not deflated it
again, so it doesn't add an Accept-Encoding header.

Then if a downstream module makes the content vary (e.g. by encoding as
"br" for Chrome), then that's the module that should be re-adding
Vary:Accept-Encoding.

This behavior makes sense (at least to me) :)

-Josh

**Comment by Lofesa** [comment]
Yes, this behavior is the desired, but things are as they are. Google brotli module for nginx don´t add the header (and I think that Cloudflare brotli module for nginx neither).

**Comment by jmarantz** [comment]
So, one option is to report bugs to the github projects for the Brotli
modules to add Vary:Accept-Encoding headers.

**Comment by Lofesa** [comment]
Done. Fingers crossed. ;-)

**Comment by Lofesa** [comment]
I found a workaround that post here for share it.
set pagespeed HttpCacheCompressionLevel 0; and enable gzip_vary on; this make resources be served by brotli and have the vary: acept-encoding

**Comment by centminmod** [comment]
having similar problem though only happens in IE/MS Edge browsers https://community.centminmod.com/threads/site-broken-in-internet-explorer-edge.9701/

wpt ms edge result for my forums at https://community.centminmod.com/ with screenshot https://www.webpagetest.org/result/170113_BA_1CW2/2/screen_shot/

> nginx -V
> nginx version: nginx/1.11.8
> built by gcc 5.3.1 20160406 (Red Hat 5.3.1-6) (GCC) 
> built with OpenSSL 1.0.2j  26 Sep 2016
> TLS SNI support enabled
> configure arguments: --with-ld-opt='-ljemalloc -Wl,-z,relro -Wl,-rpath,/usr/local/lib' --with-cc-opt='-m64 -march=native -DTCP_FASTOPEN=23 -g -O3 -fstack-protector-strong --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wno-deprecated-declarations' --sbin-path=/usr/local/sbin/nginx --conf-path=/usr/local/nginx/conf/nginx.conf --with-http_stub_status_module --with-http_secure_link_module --add-module=../nginx-module-vts --with-libatomic --with-http_gzip_static_module --add-dynamic-module=../ngx_brotli --add-dynamic-module=../ngx_pagespeed-1.12.34.2-beta --with-http_sub_module --with-http_addition_module --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-stream_geoip_module=dynamic --with-stream_realip_module --with-stream_ssl_preread_module --with-threads --with-stream=dynamic --with-stream_ssl_module --with-http_realip_module --add-dynamic-module=../ngx-fancyindex-0.4.0 --add-module=../ngx_cache_purge-2.3 --add-module=../ngx_devel_kit-0.3.0 --add-module=../set-misc-nginx-module-0.31 --add-module=../echo-nginx-module-0.60 --add-module=../redis2-nginx-module-0.13 --add-module=../ngx_http_redis-0.3.7 --add-module=../memc-nginx-module-0.17 --add-module=../srcache-nginx-module-0.31 --add-module=../headers-more-nginx-module-0.32 --with-pcre=../pcre-8.39 --with-pcre-jit --with-http_ssl_module --with-http_v2_module --with-openssl=../openssl-1.0.2j

```
brotli on;
brotli_static on;
brotli_min_length 1000;
brotli_buffers 32 8k;
brotli_comp_level 5;
brotli_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;
```
and
```
        gzip on;
        gzip_vary   on;
        gzip_disable "MSIE [1-6]\.";
        gzip_static on;
        gzip_min_length   1400;
        gzip_buffers      32 8k;
        gzip_http_version 1.0;
        gzip_comp_level 6;
        gzip_proxied    any;
        gzip_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;
```

**Comment by oschaaf** [comment]
@centminmod reading up https://community.centminmod.com/threads/site-broken-in-internet-explorer-edge.9701/ it looks like this resolved, right?

**Comment by centminmod** [comment]
@oschaaf unfortunately not resolved, only fix is to disable ngx_brotli

**Comment by ariq01** [comment]
Still not resolved? When i'm try to implement ngx_brotli with ngx_pagespeed on my nginx. Nginx error can't run
