### ISSUE TITLE
pagespeed mixes headers between location/alias block and fallback (causing decoding errors)

### ISSUE THREAD

**Issue by rbu** [pagespeed/ngx_pagespeed#1435]
I am using nginx 1.10.3 with ngx_pagespeed changeset 6ced8c0f651a4e14fd0e8e2fc1318983b64aa7e7 with PageSpeed PSOL version 1.7.30.4.

nginx is serving access via a backend service, but can access some static assets locally. A minified, but incomplete config:
```
server {
    pagespeed MapOriginDomain 127.0.0.1:3281 https://*;
    pagespeed LoadFromFile https://example.com/static/ /home/example/static/;

    location /static/ {
        alias /home/example/static/;
        gzip on;
        gzip_proxied any;
        gzip_vary on;
        add_header    Cache-Control  public;
        expires       @21h30m;
    }
    location / {
        proxy_pass http://127.0.0.1:3281;
        gzip on;
        gzip_proxied any;
        gzip_vary on;
    }
}
```

Given the following request
```
GET /static/logo.svg HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: example.com
User-Agent: HTTPie/0.9.4
```

I have *two* results that are being served, one correct and one incorrect. Both persist for a little while, but they randomly change back and forth with no apparent pattern.

The correct result:
```
HTTP/1.1 200 OK
Cache-Control: max-age=32533, public, s-maxage=10
Connection: keep-alive
Content-Encoding: gzip
Content-Type: image/svg+xml
Date: Wed, 05 Jul 2017 12:27:47 GMT
ETag: W/"595a634f-148e"
Expires: Wed, 05 Jul 2017 21:30:00 GMT
Keep-Alive: timeout=15
Last-Modified: Mon, 03 Jul 2017 15:31:27 GMT
Server: nginx
Transfer-Encoding: chunked

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

The incorrect result:
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=33047, public, s-maxage=10
Connection: keep-alive
Content-Encoding: gzip
Content-Length: 2280
Content-Type: image/svg+xml; charset=UTF-8
Date: Wed, 05 Jul 2017 12:19:04 GMT
ETag: W/"PSA-mdyLQJfkl7"
ETag: "595a634f-148e"
Expires: Wed, 05 Jul 2017 21:30:00 GMT
Keep-Alive: timeout=15
Last-Modified: Mon, 03 Jul 2017 15:31:27 GMT
Server: Apache/2.2.15 (CentOS)
Vary: Accept-Encoding
X-Original-Content-Length: 5262


http: error: ContentDecodingError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
```

Notably, the incorrect result contains Headers such as "Server" that could only have been set by the backend server in the MapOriginalDomain. That server is also seeing requests to the logo.svg file and responds correctly (not applying compression). Note that curl shows the http response body as plain text even when ```httpie``` fails to decode (but I am not 100% sure that the transfer encoding is actually plain text).

**Comment by oschaaf** [comment]
1.7.30.4 is quite old (March 24, 2014). Lots of things have been fixed since then (including this, I think), and also including *security updates*.
IMHO It's a good idea to upgrade!

**Comment by rbu** [comment]
Apologies, my version information was incorrect. This was on nginx 1.10.3 with pagspeed 1.12.34.2-beta as provided by https://copr.fedorainfracloud.org/coprs/kyl191/nginx-stable-pagespeed/build/506731/

**Comment by oschaaf** [comment]
@rbu thanks for updating the version info, re-opening.

**Comment by oschaaf** [comment]
I haven't been able to try and reproduce this yet, but one thing that stands out is that this looks ambiguous at the `server{}` level:

```
    pagespeed MapOriginDomain 127.0.0.1:3281 https://*;
    pagespeed LoadFromFile https://example.com/static/ /home/example/static/;
```

The url space covered by `MapOriginDomain` overlaps with the one that `LoadFromFile` covers.
I wonder if moving `LoadFromFile` into `location /static/ {..}` and `MapOriginDomain` into `location / {..}` will give you consistent results?

**Comment by rbu** [comment]
Thank you for the feedback.

Adding the "pagespeed LoadFromFile" directive into a location is not allowed (nginx: [emerg] "pagespeed" directive "LoadFromFile" cannot be set at this scope), but I have moved the pagespeed MapOriginDomain directory to the "/" a location. Interestingly, I am still seeing the issue with that configuration.

**Comment by oschaaf** [comment]
@rbu My apologies, somehow this didn't ring a bell earlier. But I think this has been fixed via https://github.com/pagespeed/mod_pagespeed/pull/1497 at the bleeding edge.

**Comment by rbu** [comment]
Ah thank you for the pointer, I'll try with that version and report back if it's not fixed.

**Comment by rbu** [comment]
Any chance of seeing this fixed in a release? As v1.12.34.2-stable is identical to the beta, it doesn't contain the fix.
